version: '3'

services:
  homepage:
    image: wetagustin/vps-homepage:1.0.5
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=agustinwet.online
      - LETSENCRYPT_HOST=agustinwet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

  typescript-api:
    image: wetagustin/vps-typescript-api:latest
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=api.agustinwet.online
      - LETSENCRYPT_HOST=api.agustinwet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: nginx-proxy
