version: '3'

services:
  homepage:
    image: wetagustin/vps-homepage:1.0.0
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=agustinwet.online
      - LETSENCRYPT_HOST=agustinwet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: nginx-proxy
