version: '3'

services:
  homepage:
    image: wetagustin/vps-homepage:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=awet.online
      - LETSENCRYPT_HOST=awet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

  typescript-api:
    image: wetagustin/ts-api:latest
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=api.awet.online
      - LETSENCRYPT_HOST=api.awet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

  vps-spring:
    image: wetagustin/vps-spring:latest
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=spring.awet.online
      - LETSENCRYPT_HOST=spring.awet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: nginx-proxy
