version: '3'

services:
  homepage:
    image: wetagustin/vps-homepage:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=awet.online
      - LETSENCRYPT_HOST=awet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

  typescript-api:
    image: wetagustin/ts-api:latest
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=api.awet.online
      - LETSENCRYPT_HOST=api.awet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

  spring-api:
    image: wetagustin/spring-api:latest
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=spring.awet.online
      - LETSENCRYPT_HOST=spring.awet.online
      - LETSENCRYPT_EMAIL=wet.4gustin@gmail.com
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: nginx-proxy
